[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_fixers = {
\   '*': ['trim_whitespace'],
\   'python': ['autopep8', 'black', 'isort'],
\   'tex': ['textlint'],
\}
let g:ale_linters = {
 \  'tex': ['textlint'],
 \  'python': ['pylint'],
 \}
" Set this variable to 1 to fix files when you save them.
let g:ale_fix_on_save = 1
let g:ale_sign_column_always = 1
" エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
" エラー表示の列を常時表示
let g:ale_sign_column_always = 1

" ファイルを開いたときにlint実行
let g:ale_lint_on_enter = 1
" ファイルを保存したときにlint実行
let g:ale_lint_on_save = 1

" lint結果をロケーションリストとQuickFixには表示しない
" 出てると結構うざいしQuickFixを書き換えられるのは困る
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
let g:ale_open_list = 0
let g:ale_keep_list_window_open = 0
'''
