[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'
[[plugins]]
repo = 'raphamorim/lucario'

hook_add = '''
  autocmd MyAutoCmd ColorScheme * highlight Normal ctermbg=none
  autocmd MyAutoCmd ColorScheme * highlight LineNr ctermbg=none
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  if has('unix')
    autocmd MyAutoCmd VimEnter * nested colorscheme lucario
  endif
'''
