# Text, Tex, Markdown {{{
# Insert->Normalの時に自動的に日本語入力をローマ字入力に切り替える
[[plugins]]
repo = 'lilydjwg/fcitx.vim'
if = '''has('unix')'''
on_ft = ['tex','text','markdown']

[[plugins]]
repo = 'ujihisa/neco-look'
depends = 'deopelete.nvim'
if = '''has('unix')'''
on_ft = ['tex','text','markdown']

[[plugins]]
repo = 'kana/vim-smartchr'
if = '''has('unix')'''
on_ft = ['tex','text','markdown']

[[plugins]]
repo = 'tyru/eskk.vim'


# }}}
# Toml {{{
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = 'toml'
# }}}
# HTML {{{
# Highlight HTML tags
[[plugins]]
repo = 'Valloric/MatchTagAlways'
on_ft = 'html'
# }}}
# Python {{{
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
# }}}
# Markdown {{{
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
    let g:vim_markdown_fenced_languages = ['bash=bash']
'''

[[plugins]] # :PrevimOpen 指定したブラウザにmdがレンダリングされる
# 依存 pip install docutils
repo = 'previm/previm'
if = '''has('mac') || has('unix')'''
on_ft = 'markdown'
hook_add = '''
" open with Google Chrome
if has('unix')
    let g:previm_open_cmd = 'google-chrome'
elseif has('mac')
    let g:previm_open_cmd = 'open -a Google\ Chrome'
endif
" リアルタイムにプレビュー
let g:previm_enable_realtime = 1
" プレビュー時にヘッダーを表示
let g:previm_show_header = 1

autocmd MyAutoCmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} | set filetype=markdown
'''

[[plugins]] # :Toc ヘッダのアウトライン表示
repo = 'godlygeek/tabular'
on_ft = 'markdown'
hook_add = '''
" cucumbertables.vim https://gist.github.com/tpope/287147
inoremap <silent> <Bar>   <Bar><Esc>:call <SID>align()<CR>a

function! s:align()
  let p = '^\s*|\s.*\s|\s*$'
  if exists(':Tabularize') && getline('.') =~# '^\s*|' && (getline(line('.')-1) =~# p || getline(line('.')+1) =~# p)
    let column = strlen(substitute(getline('.')[0:col('.')],'[^|]','','g'))
    let position = strlen(matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*'))
    Tabularize/|/l1
    normal! 0
    call search(repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.'))
  endif
endfunction
'''
# }}}
