[ftplugin] #{{{
css = 'setlocal iskeyword+=-'

help = 'setlocal nolist nonumber norelativenumber'

html_javascript = ''' "{{{
  setlocal tabstop=2
  setlocal shiftwidth=2
  setlocal softtabstop=2
"}}} '''

json = ''' "{{{
  setlocal tabstop=4
  setlocal shiftwidth=4
  setlocal softtabstop=4
  setlocal nocursorcolumn
"}}} '''

python = ''' "{{{
  setlocal tabstop=4
  setlocal softtabstop=4
  setlocal shiftwidth=4
"}}} '''

toml = ''' "{{{
  setlocal foldmethod=marker
  setlocal tabstop=2
  setlocal softtabstop=0
  setlocal shiftwidth=2
"}}} '''

vim = ''' "{{{
  setlocal foldmethod=marker
  setlocal tabstop=2
  setlocal softtabstop=0
  setlocal shiftwidth=2
"}}} '''

dockerfile = 'setlocal foldmethod=indent'
#}}}
