[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
if = '''has('unix') || has('mac')'''
hook_post_source = '''
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'tex': g:vimtex#re#deoplete
    \})
'''
hook_add = '''
if has('mac')
  let g:vimtex_view_general_viewer='skim'
elseif has('win64')
  let g:vimtex_view_general_viewer='C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe'
else
  let g:vimtex_view_general_viewer='evince'
endif
if has('nvim')
  let g:vimtex_compiler_progname
        \ = 'nvr'
endif
let g:vimtex_fold_manual = 1
'''

